services:
  host-a:
    build: ./rstracer
    container_name: rstracer-001
    hostname: docker-rstracer-001
    networks:
      network-a:
        ipv4_address: 220.189.5.10
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_PORT=8501

  host-b:
    build: ./rstracer
    container_name: rstracer-002
    hostname: docker-rstracer-002
    networks:
      network-a:
        ipv4_address: 220.189.5.20
    ports:
      - "8502:8502"
    environment:
      - STREAMLIT_PORT=8502

  host-c:
    build: ./rstracer
    container_name: rstracer-003
    hostname: docker-rstracer-003
    networks:
      network-a:
        ipv4_address: 220.189.5.30
    ports:
      - "8503:8503"
    environment:
      - STREAMLIT_PORT=8503

  host-d:
    build: ./rstracer
    container_name: rstracer-004
    hostname: docker-rstracer-004
    networks:
      network-a:
        ipv4_address: 220.189.5.40
    ports:
      - "8504:8504"
    environment:
      - STREAMLIT_PORT=8504

  host-e:
    build: ./rstracer
    container_name: rstracer-005
    hostname: docker-rstracer-005
    networks:
      network-b:
        ipv4_address: 117.210.5.10
    ports:
      - "8505:8505"
    environment:
      - STREAMLIT_PORT=8505

  host-f:
    build: ./rstracer
    container_name: rstracer-006
    hostname: docker-rstracer-006
    networks:
      network-b:
        ipv4_address: 117.210.5.20
    ports:
      - "8506:8506"
    environment:
      - STREAMLIT_PORT=8506

networks:
  network-a:
    name: network-a
    ipam:
      driver: default
      config:
        - subnet: 220.189.0.0/16
          ip_range: 220.189.5.0/24
  network-b:
    name: network-b
    ipam:
      driver: default
      config:
        - subnet: 117.210.0.0/16
          ip_range: 117.210.5.0/24